---
language: ruby
cache: bundler
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test SPEC_OPTS='--format documentation'
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
env:
  matrix:
    - PUPPET_VERSION="~> 3.4.0"
    - PUPPET_VERSION="~> 3.5.0"
    - PUPPET_VERSION="~> 3.6.0"
    - PUPPET_VERSION="~> 3.7.0"
matrix:
  fast_finish: true
  exclude:
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.4.0"
